# Generated by Django 3.1.4 on 2020-12-12 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subcategoty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='myshop.category'),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
