# Generated by Django 3.1.4 on 2020-12-12 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0003_auto_20201212_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='subcategoty',
            new_name='category',
        ),
    ]
